version: '3.1'

services:
  proxy:
    image: traefik:1.7.9 
    command: --api --docker 
    ports:
      - "${LIST_TRAEFIK_HTTP_EXT_PORT}:80"     # main proxy port
      - "${LIST_TRAEFIK_HTTPS_EXT_PORT}:443"     # https proxy port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/acme.json:/acme.json
    restart: unless-stopped
    environment:
      CLOUDFLARE_EMAIL: ${CF_API_EMAIL}
      CLOUDFLARE_API_KEY: ${CF_API_KEY}  
    labels:
      - "traefik.proxy.frontend.rule=PathPrefixStrip:/proxy/"
      - "traefik.proxy.port=8080"
      - "traefik.api.frontend.rule=PathPrefix:/api/"
      - "traefik.api.port=8080"
      - "traefik.health.frontend.rule=PathPrefix:/health"
      - "traefik.health.port=8080"

  web:
    image: airenas/ear-app:${EAR_APP_VERSION}
    restart: unless-stopped
    labels:
     - "traefik.enable=true"
     - "traefik.http.frontend.rule=PathPrefixStrip:/ausis/"
     - "traefik.http.port=8000"

  upload-service:
    image: airenas/list-upload-service:${UPLOAD_SERVICE_VERSION}
    restart: unless-stopped
    volumes:
      - fileStorage:/data
    depends_on: 
      - rabbitmq  
      - mongo
    environment:
      MESSAGESERVER_URL: ${LIST_RABBITMQ_URL}
      MESSAGESERVER_USER: ${LIST_RABBITMQ_USER}
      MESSAGESERVER_PASS: ${LIST_RABBITMQ_PASS}
      MONGO_URL: ${LIST_MONGO_URL}
    labels:
     - "traefik.frontend.rule=PathPrefixStrip:/ausis/transcriber/"
     - "traefik.port=8000"  
  
  result-service:
    image: airenas/list-result-service:${RESULT_SERVICE_VERSION}
    restart: unless-stopped
    volumes:
      - fileStorage:/data
    depends_on: 
      - mongo
    environment:
      MONGO_URL: ${LIST_MONGO_URL}
    labels:
     - "traefik.frontend.rule=PathPrefixStrip:/ausis/result.service/"
     - "traefik.port=8000"     

  status-service:
    image: airenas/list-status-service:${SERVICE_VERSION}
    restart: unless-stopped
    depends_on: 
      - mongo
      - rabbitmq
    environment:
      MESSAGESERVER_URL: ${LIST_RABBITMQ_URL}
      MESSAGESERVER_USER: ${LIST_RABBITMQ_USER}
      MESSAGESERVER_PASS: ${LIST_RABBITMQ_PASS}
      MONGO_URL: ${LIST_MONGO_URL}    
    labels:
     - "traefik.frontend.rule=PathPrefixStrip:/ausis/status.service/"
     - "traefik.port=8000" 
  
  manager-service:
    image: airenas/list-manager-service:${SERVICE_VERSION}
    restart: unless-stopped
    depends_on: 
      - mongo
      - rabbitmq
    environment:
      MESSAGESERVER_URL: ${LIST_RABBITMQ_URL}
      MESSAGESERVER_USER: ${LIST_RABBITMQ_USER}
      MESSAGESERVER_PASS: ${LIST_RABBITMQ_PASS}
      MONGO_URL: ${LIST_MONGO_URL}  

  audio-prepare-service:
    image: airenas/list-audio-prepare-service:${SERVICE_VERSION}
    restart: unless-stopped
    depends_on: 
      - rabbitmq
    environment:
      MESSAGESERVER_URL: ${LIST_RABBITMQ_URL}
      MESSAGESERVER_USER: ${LIST_RABBITMQ_USER}
      MESSAGESERVER_PASS: ${LIST_RABBITMQ_PASS}  
    volumes:
      - fileStorage:/data

  diarization-service:
    image: airenas/list-diarization-service:${SERVICE_VERSION}
    restart: unless-stopped
    depends_on: 
      - rabbitmq
    environment:
      MESSAGESERVER_URL: ${LIST_RABBITMQ_URL}
      MESSAGESERVER_USER: ${LIST_RABBITMQ_USER}
      MESSAGESERVER_PASS: ${LIST_RABBITMQ_PASS}  
    volumes:
      - fileStorage:/data    
      - appsStorage:/apps
      - modelsStorage:/models    
  
  transcription-service:
    image: airenas/list-transcription-service:${SERVICE_VERSION}
    restart: unless-stopped
    depends_on: 
      - rabbitmq
    environment:
      MESSAGESERVER_URL: ${LIST_RABBITMQ_URL}
      MESSAGESERVER_USER: ${LIST_RABBITMQ_USER}
      MESSAGESERVER_PASS: ${LIST_RABBITMQ_PASS}  
    volumes:
      - fileStorage:/data    
      - appsStorage:/apps
      - modelsStorage:/models      
  
  result-make-service:
    image: airenas/list-result-make-service:${TR_RESULT_SERVICE_VERSION}
    restart: unless-stopped
    depends_on: 
      - rabbitmq
    environment:
      MESSAGESERVER_URL: ${LIST_RABBITMQ_URL}
      MESSAGESERVER_USER: ${LIST_RABBITMQ_USER}
      MESSAGESERVER_PASS: ${LIST_RABBITMQ_PASS}  
    volumes:
      - fileStorage:/data    
      - appsStorage:/apps
      - modelsStorage:/models 

  inform-service:
    image: airenas/list-inform-service:${INFORM_SERVICE_VERSION}
    restart: unless-stopped
    depends_on: 
      - rabbitmq
      - mongo
    environment:
      MESSAGESERVER_URL: ${LIST_RABBITMQ_URL}
      MESSAGESERVER_USER: ${LIST_RABBITMQ_USER}
      MESSAGESERVER_PASS: ${LIST_RABBITMQ_PASS}
      MONGO_URL: ${LIST_MONGO_URL}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      MAIL_URL: ${MAIL_URL}     

# ########### db & broker
  mongo:
    image: mongo:4.1.1
    environment:
      MONGO_DATA_DIR: "/data/db"
      MONGO_LOG_DIR: "/dev/null"
      MONGO_INITDB_ROOT_USERNAME: ${LIST_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${LIST_MONGO_PASS}
    volumes:
      - mongo:/data/db
    restart: unless-stopped     
    command: mongod --logpath=/dev/null # --quiet
    labels:
     - "traefik.frontend.rule=PathPrefixStrip:/mongo/"
     - "traefik.port=27017"

  rabbitmq:
    image: "rabbitmq:3.7-management"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "0eaf0f4e-7078-44b0-970d-1c3d1277f9f2"
      RABBITMQ_DEFAULT_USER: ${LIST_RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${LIST_RABBITMQ_PASS}
      RABBITMQ_DEFAULT_VHOST: "/"
    labels:
      NAME: "rabbitmq"
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    restart: unless-stopped  
    labels:
     - "traefik.frontend.rule=PathPrefixStrip:/rabbit/"
     - "traefik.port=15672"  

# ########### volumes 
volumes:
  fileStorage:
    driver_opts:
      type: none
      device: ${LIST_VOLUMES_DIR}fileStorage
      o: bind

  appsStorage:
    driver_opts:
      type: none
      device: ${LIST_VOLUMES_DIR}apps
      o: bind

  modelsStorage:
    driver_opts:
      type: none
      device: ${LIST_VOLUMES_DIR}models
      o: bind          

  rabbitmq:
    driver_opts:
      type: none
      device: ${LIST_VOLUMES_DIR}rabbitmq
      o: bind     

  mongo:
    driver_opts:
      type: none
      device: ${LIST_VOLUMES_DIR}mongo
      o: bind