#  Template Go (Golang) build

#  This template allows you to validate your Go (Golang) code.
#  The workflow allows running tests, build and code linting on the default branch.

image: golang:1.17

pipelines:
  default:
    - parallel:
        - step:
            name: Test code
            runs-on:
              - "self.hosted"
              - "linux"
            script:
              - cd src/tools/ 
              - make generate/mocks
              - make test/report
        - step:
            name: Test vulnerabilities
            runs-on:
              - "self.hosted"
              - "linux"
            script:
              - cd src/tools/ 
              - make generate/mocks
              - make test/snyk SNYK_TOKEN=${SNYK_TOKEN} tty=
            services:
              - docker      
        - step:
            name: Lint code
            runs-on:
              - "self.hosted"
              - "linux"
            script:
              - cd src/tools/
              - make generate/mocks
              - make test/lint
