#  Template Go (Golang) build

#  This template allows you to validate your Go (Golang) code.
#  The workflow allows running tests, build and code linting on the default branch.

image: golang:1.17

pipelines:
  default:
    - parallel:
        - step:
            name: Test and Lint own
            runs-on:
              - "self.hosted"
              - "linux"
            script:
              - cd src/tools/ 
              - make generate/mocks
              - make test/report
        - step:
            name: Lint code
            runs-on:
              - "self.hosted"
              - "linux"
            script:
              - cd src/tools/
              - make generate/mocks
              - make test/lint
