FROM ubuntu:16.04
LABEL Description="This image is used as base with Ubuntu and Make installed" \ 
      Maintainer="airenass@gmail.com" Vendor="Airenas Vaiciunas" Version="1.0" 

RUN apt-get update && apt-get install -y build-essential libatlas-base-dev
