-include Makefile.options
###################################################################################
test_dir=fs
id?=8khz
DENOISE_APP=../../../sfgparse/sfg
DIARIZATION_APP=$(MAKE) -f Makefile.test fakeSeg; env; echo cmdparams 
DIARIZATION_APP_REAL=apps/diarization.sh 
FIX_SEGMENTS_APP=../../../deploy/local/diarization/deploy/fix.segments
SEND_METRIC_APP=echo SEND_METRIC: 
MODELS_ROOT=../../../volumes/models/diarization
###################################################################################
LOCALCLASSPATH?=LIUM_SpkDiarization-4.2.jar
LOCALCLASSPATH?=../../../../lium-spkdiarization/jar/LIUM_SpkDiarization-8.4.jar
ns?=1

.EXPORT_ALL_VARIABLES:

test: 
	${MAKE} ${test_dir}/decoded/trans/${id}/.diarization.done

fakeSeg:
	echo "prepared 1 198 900 M S U S2" > $(test_dir)/decoded/diarization/${id}/show.seg
	echo "prepared 1 2634 1074 M S U S1" >> $(test_dir)/decoded/diarization/${id}/show.seg
	echo "prepared 1 1386 1080 M S U S1" >> $(test_dir)/decoded/diarization/${id}/show.seg
	echo "prepared 1 3990 1002 M S U S0" >> $(test_dir)/decoded/diarization/${id}/show.seg

clean:
	rm -rf $(test_dir)/decoded/trans/${id}
	rm -rf $(test_dir)/decoded/diarization/${id}

test-speakers: 
	NUMBER_OF_SPEAKERS=$(ns) ${MAKE} ${test_dir}/decoded/trans/${id}/.diarization.done

test-real: 
	DIARIZATION_APP=$(DIARIZATION_APP_REAL) ${MAKE} ${test_dir}/decoded/trans/${id}/.diarization.done


