OUTPUT_ROOT=/home/airenas/projects/list/volumes/fileStorage/decoded
INPUT_ROOT=/home/airenas/projects/list/volumes/fileStorage/audio.prepared
APPS_ROOT=/home/airenas/projects/list/volumes/apps/diarization
MODELS_ROOT=/home/airenas/projects/list/volumes/models/diarization
