package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"strconv"
	"strings"
	"time"

	"bitbucket.org/airenas/list/src/tools/internal/pkg/ioutil"
	"bitbucket.org/airenas/list/src/tools/internal/pkg/lattice"
	"github.com/pkg/errors"
)

func main() {
	log.SetOutput(os.Stderr)
	flag.Usage = func() {
		fmt.Fprintf(os.Stderr, "Usage of %s: <input-file or stdin> <output-file or stdout>\n", os.Args[0])
		flag.PrintDefaults()
	}
	flag.Parse()

	f, err := ioutil.NewReadWrapper(flag.Arg(0))
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	destination, err := ioutil.NewWriteWrapper(flag.Arg(1))
	if err != nil {
		log.Fatal(err)
	}
	defer destination.Close()

	data, err := lattice.Read(f)
	if err != nil {
		log.Fatal(errors.Wrap(err, "Can't read lattice"))
	}
	_, err = destination.WriteString(getHeader())
	text := getWebVTT(data)
	_, err = destination.WriteString(text)
	if err != nil {
		log.Fatal(errors.Wrap(err, "Can't write result lattice"))
	}
	log.Print("Done generation")
}

type tdata struct {
	sb       strings.Builder
	speaker  string
	from, to *lattice.Word
	sbLine   strings.Builder
	sep      string
}

func getHeader() string {
	return "WEBVTT - Generated by LKSSAIS\n"
}

func getWebVTT(data []*lattice.Part) string {
	td := &tdata{}
	for _, p := range data {
		if p.Speaker != td.speaker {
			write(td)
			td.speaker = p.Speaker
		}
		for _, w := range p.Words {
			if w.Main == lattice.MainInd {
				if w.Word != lattice.SilWord {
					if td.to != nil && (lattice.Duration(w.From)-lattice.Duration(td.to.To)) > 500*time.Millisecond {
						write(td)
					}
					add(td, w)
				}
			}
		}
	}
	write(td)
	return td.sb.String()
}

func write(td *tdata) {
	if td.from != nil {
		td.sb.WriteString("\n")
		td.sb.WriteString(asString(lattice.Duration(td.from.From)))
		td.sb.WriteString(" --> ")
		td.sb.WriteString(asString(lattice.Duration(td.to.To)))
		td.sb.WriteString("\n")
		td.sb.WriteString(td.sbLine.String())
		td.sb.WriteString("\n")
	}
	td.sbLine.Reset()
	td.from = nil
	td.to = nil
	td.sep = ""
}

func add(td *tdata, w *lattice.Word) {
	if td.from == nil {
		td.from = w
	}
	td.to = w
	td.sep = writeWord(&td.sbLine, w.Word, td.sep)
	td.sep = writePunct(&td.sbLine, w.Punct)
}

func writeWord(res *strings.Builder, word, sep string) string {
	res.WriteString(sep + word)
	return " "
}

func writePunct(res *strings.Builder, punct string) string {
	if punct == "-" {
		res.WriteString(" ")
	}
	res.WriteString(punct)
	return " "
}

func asString(d time.Duration) string {
	res := ""
	ms := d.Milliseconds()
	tv := int64(ms) / time.Hour.Milliseconds()
	if tv > 0 {
		res += padString(tv, 2) + ":"
	}
	ms = ms % time.Hour.Milliseconds()
	tv = ms / time.Minute.Milliseconds()
	res += padString(tv, 2) + ":"
	ms = ms % time.Minute.Milliseconds()
	tv = ms / time.Second.Milliseconds()
	res += padString(tv, 2) + "."
	ms = ms % time.Second.Milliseconds()
	res += padString(ms, 3)
	return res
}

func padString(v int64, l int) string {
	res := strconv.Itoa(int(v))
	for len(res) < l {
		res = "0" + res
	}
	return res
}
