rule_files:
  - prometheus_rules.yml
global:
  scrape_interval: 30s 
scrape_configs:
- job_name: 'node-exporter'
  static_configs:
  - targets:
    - node-exporter:9100

- job_name: 'status-service'
  static_configs:
  - targets:
    - status-service:8000    

- job_name: 'upload-service'
  static_configs:
  - targets:
    - upload-service:8000

- job_name: 'result-service'
  static_configs:
  - targets:
    - result-service:8000        
    
- job_name: 'clean-service'
  static_configs:
  - targets:
    - clean-service:8000            

- job_name: 'metrics-collector'
  static_configs:
  - targets:
    - metrics-collector:8000
