# messageServer: 
#     url: amqp://list:list@rabbitmq:5672/
    
# mongo:
#     url: mongo 

# sendInformMessages: false

# logger:
#     level: info
#     formatter:
#         name: text
#         options: 
#             full_timestamp: true
#             timestamp_format: "2006-01-02T15:04:05.000"
