version: '3.7'

services:
  web:
    build: web
    restart: unless-stopped
    environment:
      BASE_HREF: /ausisz/
    labels:
     - "traefik.enable=true"
     - "traefik.http.frontend.rule=PathPrefixStrip:/ausisz/"
     - "traefik.http.port=8000"

  upload-service:
    build: upload
    restart: unless-stopped
    volumes:
      - fileStorage:/data
    environment:
      MESSAGESERVER_URL: ${LIST_RABBITMQ_URL}
      MESSAGESERVER_USER: ${LIST_RABBITMQ_USER}
      MESSAGESERVER_PASS: ${LIST_RABBITMQ_PASS}
      MESSAGESERVER_PREFIX: words
      MONGO_URL: ${LIST_MONGO_URL}
    labels:
     - "traefik.frontend.rule=PathPrefixStrip:/ausisz/transcriber/"
     - "traefik.port=8000" 
  
  result-service:
    build: result
    restart: unless-stopped
    volumes:
      - fileStorage:/data
    environment:
      MONGO_URL: ${LIST_MONGO_URL}
    labels:
     - "traefik.frontend.rule=PathPrefixStrip:/ausisz/result.service/"
     - "traefik.port=8000"  

  status-service:
    build: status
    restart: unless-stopped
    environment:
      MESSAGESERVER_URL: ${LIST_RABBITMQ_URL}
      MESSAGESERVER_USER: ${LIST_RABBITMQ_USER}
      MESSAGESERVER_PASS: ${LIST_RABBITMQ_PASS}
      MESSAGESERVER_PREFIX: words
      MONGO_URL: ${LIST_MONGO_URL}    
    labels:
     - "traefik.frontend.rule=PathPrefixStrip:/ausisz/status.service/"
     - "traefik.port=8000" 
  
  manager-service:
    build: manager
    restart: unless-stopped
    environment:
      MESSAGESERVER_URL: ${LIST_RABBITMQ_URL}
      MESSAGESERVER_USER: ${LIST_RABBITMQ_USER}
      MESSAGESERVER_PASS: ${LIST_RABBITMQ_PASS}
      MESSAGESERVER_PREFIX: words
      MONGO_URL: ${LIST_MONGO_URL}

  audio-prepare-service:
    build: audio.prepare
    restart: unless-stopped
    environment:
      MESSAGESERVER_URL: ${LIST_RABBITMQ_URL}
      MESSAGESERVER_USER: ${LIST_RABBITMQ_USER}
      MESSAGESERVER_PASS: ${LIST_RABBITMQ_PASS}  
      MESSAGESERVER_PREFIX: words
    volumes:
      - fileStorage:/data

  diarization-service:
    build: diarization
    restart: unless-stopped
    environment:
      MESSAGESERVER_URL: ${LIST_RABBITMQ_URL}
      MESSAGESERVER_USER: ${LIST_RABBITMQ_USER}
      MESSAGESERVER_PASS: ${LIST_RABBITMQ_PASS}  
      MESSAGESERVER_PREFIX: words
    volumes:
      - fileStorage:/data    
      - appsStorage:/apps
      - dModelsStorageWords:/models    
  
  transcription-service:
    build: transcription
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MESSAGESERVER_URL: ${LIST_RABBITMQ_URL}
      MESSAGESERVER_USER: ${LIST_RABBITMQ_USER}
      MESSAGESERVER_PASS: ${LIST_RABBITMQ_PASS}  
      MESSAGESERVER_PREFIX: words
    volumes:
      - fileStorage:/data    
      - appsStorage:/apps
      - modelsStorageWords:/models      
  
  result-make-service:
    build: result.make
    restart: unless-stopped
    environment:
      MESSAGESERVER_URL: ${LIST_RABBITMQ_URL}
      MESSAGESERVER_USER: ${LIST_RABBITMQ_USER}
      MESSAGESERVER_PASS: ${LIST_RABBITMQ_PASS}  
      MESSAGESERVER_PREFIX: words
      PR_URL: http://punctuation-service:8080/punctuation
    volumes:
      - fileStorage:/data    
      - appsStorage:/apps
      - modelsStorageWords:/models  

  inform-service:
    build: inform
    restart: unless-stopped
    environment:
      MESSAGESERVER_URL: ${LIST_RABBITMQ_URL}
      MESSAGESERVER_USER: ${LIST_RABBITMQ_USER}
      MESSAGESERVER_PASS: ${LIST_RABBITMQ_PASS}
      MESSAGESERVER_PREFIX: words
      MONGO_URL: ${LIST_MONGO_URL}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      MAIL_URL: ${MAIL_URL_WORDS}


  tensorflow:
    image: tensorflow/serving:1.14.0
    environment:
      MODEL_NAME: punctuation
      MODEL_BASE_PATH: /models/model
    volumes:
      - punctRestorationStorage:/models
    ports:
      - ${LIST_TF_GRPC_EXT_PORT}:8500
      - ${LIST_TF_EXT_PORT}:8501
    restart: unless-stopped 
  
  punctuation-service:
    build: punctuation
    restart: unless-stopped
    volumes:
      - punctRestorationStorage:/model
    environment:
      TF_URL: tensorflow:8500
    labels:
     - "traefik.frontend.rule=PathPrefixStrip:/punctuation/"
     - "traefik.port=8080"
  
  clean-service:
    build: clean
    restart: unless-stopped
    environment:
      MONGO_URL: ${LIST_MONGO_URL}
    volumes:
      - fileStorage:/data    

########### volumes 
volumes:
  fileStorage:
    driver_opts:
      type: none
      device: ${LIST_VOLUMES_DIR}fileStorage
      o: bind

  appsStorage:
    driver_opts:
      type: none
      device: ${LIST_VOLUMES_DIR}apps
      o: bind

  dModelsStorageWords:
    driver_opts:
      type: none
      device: ${LIST_VOLUMES_DIR}models
      o: bind      

  modelsStorageWords:
    driver_opts:
      type: none
      device: ${MODEL_DIR_WORDS}
      o: bind   

  punctRestorationStorage:
    driver_opts:
      type: none
      device: ${PUNCT_RESTORATION_DIR_WORDS}
      o: bind                       

networks:
  default:
    external:
      name: list_default