## Local machine dirs
GO_SRC_DIR=/home/airenas/projects/listgo
SRC_DIR=/home/airenas/projects/list/src

## Services
TRANSCRIPTION_SERVICE_VERSION=2.1
TR_RESULT_SERVICE_VERSION=2.1


## non configurable
docker_container_prefix=list-
commit_count=$(shell git rev-list --count HEAD)
go_build_cmd=CGO_ENABLED=0 go build -installsuffix -cgo
