-include Makefile.options

####################################################################################
test_dir=fs
id?=123
SEND_METRIC_APP=echo SEND_METRIC: 
####################################################################################

.EXPORT_ALL_VARIABLES:

info: 
	${MAKE} info ID=$(id)

test: 
	${MAKE} ${test_dir}/audio.in/${id}/.split.done

clean:
	rm -rf ${test_dir}/audio.in/${id}
