worker:
    name: ResultMakeWorker
    command: make /data/results/{ID}/resultFinal.txt /data/results/{ID}/lat.txt /data/results/{ID}/lat.nb10.txt
    workingDir: /cmd/
    resultFile: /data/results/{ID}/resultFinal.txt
    logFile: /data/logs/{ID}.log
    preloadKeyPrefix: rescore-preload

recognizerConfig:
    path: /models/config/

registry:
    queue: ResultMakeWorker_Registry
    heartbeat: 30s  

# logger:
#     level: info
#     formatter:
#         name: text
#         options: 
#             full_timestamp: true
#             timestamp_format: "2006-01-02T15:04:05.000"
