---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: aft
spec:
  type: ClusterIP
  ports:
  - name: client-in
    port: 27017
    protocol: TCP
    targetPort: 27017 
  selector:
    app: mongo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: aft  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      nodeSelector:
        nodetype: transcriber
      volumes:
        - name: mongo-vol
          persistentVolumeClaim:
             claimName: mongo
      containers:
      - name: mongo
        image: mongo:4.1.1
        ports:
        - containerPort: 27017
          name: http
        command: ["mongod"]
        args: ["--logpath=/dev/null"]  
        env:
        - name: MONGO_DATA_DIR
          value: /data/db  
        - name: MONGO_LOG_DIR
          value: "/dev/null"   
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-login
              key: username  
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-login
              key: password
        volumeMounts:
        - name: mongo-vol 
          mountPath: /data/db
