### upload service
---
apiVersion: v1
kind: Service
metadata:
  name: upload
  namespace: aft
spec:
  type: ClusterIP
  ports:
  - name: client-in
    port: 8000
    protocol: TCP
    targetPort: 8000 
  selector:
    app: upload
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload
  namespace: aft  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload
  template:
    metadata:
      labels:
        app: upload
    spec:
      nodeSelector:
        nodetype: transcriber
      volumes:
      - name: filestorage-vol
        persistentVolumeClaim:
          claimName: filestorage
      containers:
      - name: upoad
        image: airenas/list-upload-service:v0.5beta
        ports:
        - containerPort: 8000
          name: client
        env:
        - name: MESSAGESERVER_URL
          value: rabbitmq:5672  
        - name: MESSAGESERVER_USER
          valueFrom:
            secretKeyRef:
              name: rabbit-mq-login
              key: username  
        - name: MESSAGESERVER_PASS
          valueFrom:
            secretKeyRef:
              name: rabbit-mq-login
              key: password
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongo-login
              key: username  
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: mongo-login
              key: password      
        - name: MONGO_URL
          value: mongodb://$(MONGO_USER):$(MONGO_PASS)@mongo:27017
        volumeMounts:
        - name: filestorage-vol 
          mountPath: /data
---
### manager service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: aft  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manager
  template:
    metadata:
      labels:
        app: manager
    spec:
      nodeSelector:
        nodetype: transcriber
      containers:
      - name: manager
        image: airenas/list-manager-service:v0.3beta
        env:
        - name: MESSAGESERVER_URL
          value: rabbitmq:5672  
        - name: MESSAGESERVER_USER
          valueFrom:
            secretKeyRef:
              name: rabbit-mq-login
              key: username  
        - name: MESSAGESERVER_PASS
          valueFrom:
            secretKeyRef:
              name: rabbit-mq-login
              key: password
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongo-login
              key: username  
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: mongo-login
              key: password      
        - name: MONGO_URL
          value: mongodb://$(MONGO_USER):$(MONGO_PASS)@mongo:27017