### upload service
---
apiVersion: v1
kind: Service
metadata:
  name: upload
  namespace: aft
spec:
  type: ClusterIP
  ports:
  - name: client-in
    port: 8000
    protocol: TCP
    targetPort: 8000 
  selector:
    app: upload
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload
  namespace: aft  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload
  template:
    metadata:
      labels:
        app: upload
    spec:
      nodeSelector:
        nodetype: transcriber
      volumes:
      - name: filestorage-vol
        persistentVolumeClaim:
          claimName: filestorage
      - name: modelstorage-vol
        persistentVolumeClaim:
          claimName: modelstorage-2    
      containers:
      - name: upoad
        image: airenas/list-upload-service:1.3.663
        ports:
        - containerPort: 8000
          name: client
        env:
        - name: MESSAGESERVER_URL
          value: rabbitmq:5672  
        - name: MESSAGESERVER_USER
          valueFrom:
            secretKeyRef:
              name: rabbit-mq-login
              key: username  
        - name: MESSAGESERVER_PASS
          valueFrom:
            secretKeyRef:
              name: rabbit-mq-login
              key: password
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongo-login
              key: username  
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: mongo-login
              key: password      
        - name: MONGO_URL
          value: mongodb://$(MONGO_USER):$(MONGO_PASS)@mongo:27017
        volumeMounts:
        - name: filestorage-vol 
          mountPath: /data
        - name: modelstorage-vol 
          mountPath: /models  
---
### status service
apiVersion: v1
kind: Service
metadata:
  name: status
  namespace: aft
spec:
  type: ClusterIP
  ports:
  - name: client-in
    port: 8000
    protocol: TCP
    targetPort: 8000 
  selector:
    app: status
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: status
  namespace: aft  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: status
  template:
    metadata:
      labels:
        app: status
    spec:
      nodeSelector:
        nodetype: transcriber
      containers:
      - name: status
        image: airenas/list-status-service:1.3.658
        ports:
        - containerPort: 8000
          name: client
        env:
        - name: MESSAGESERVER_URL
          value: rabbitmq:5672  
        - name: MESSAGESERVER_USER
          valueFrom:
            secretKeyRef:
              name: rabbit-mq-login
              key: username  
        - name: MESSAGESERVER_PASS
          valueFrom:
            secretKeyRef:
              name: rabbit-mq-login
              key: password
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongo-login
              key: username  
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: mongo-login
              key: password      
        - name: MONGO_URL
          value: mongodb://$(MONGO_USER):$(MONGO_PASS)@mongo:27017
---
### result service
apiVersion: v1
kind: Service
metadata:
  name: result
  namespace: aft
spec:
  type: ClusterIP
  ports:
  - name: client-in
    port: 8000
    protocol: TCP
    targetPort: 8000 
  selector:
    app: result
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  namespace: aft  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      nodeSelector:
        nodetype: transcriber
      volumes:
      - name: filestorage-vol
        persistentVolumeClaim:
          claimName: filestorage  
      containers:
      - name: result
        image: airenas/list-result-service:1.1.663
        ports:
        - containerPort: 8000
          name: client
        env:
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongo-login
              key: username  
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: mongo-login
              key: password      
        - name: MONGO_URL
          value: mongodb://$(MONGO_USER):$(MONGO_PASS)@mongo:27017
        volumeMounts:
        - name: filestorage-vol 
          mountPath: /data  
---
### manager service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: aft  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manager
  template:
    metadata:
      labels:
        app: manager
    spec:
      nodeSelector:
        nodetype: transcriber
      containers:
      - name: manager
        image: airenas/list-manager-service:1.1.583
        env:
        - name: MESSAGESERVER_URL
          value: rabbitmq:5672  
        - name: MESSAGESERVER_USER
          valueFrom:
            secretKeyRef:
              name: rabbit-mq-login
              key: username  
        - name: MESSAGESERVER_PASS
          valueFrom:
            secretKeyRef:
              name: rabbit-mq-login
              key: password
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongo-login
              key: username  
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: mongo-login
              key: password      
        - name: MONGO_URL
          value: mongodb://$(MONGO_USER):$(MONGO_PASS)@mongo:27017
---    
## audio preparation service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audio-prepare
  namespace: aft  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audio-prepare
  template:
    metadata:
      labels:
        app: audio-prepare
    spec:
      nodeSelector:
        nodetype: transcriber
      volumes:
      - name: filestorage-vol
        persistentVolumeClaim:
          claimName: filestorage
      - name: modelstorage-vol
        persistentVolumeClaim:
          claimName: modelstorage-2    
      containers:
      - name: audio-prepare
        image: airenas/list-audio-prepare-service:2.1.632
        env:
        - name: MESSAGESERVER_URL
          value: rabbitmq:5672  
        - name: MESSAGESERVER_USER
          valueFrom:
            secretKeyRef:
              name: rabbit-mq-login
              key: username  
        - name: MESSAGESERVER_PASS
          valueFrom:
            secretKeyRef:
              name: rabbit-mq-login
              key: password
        - name: METRICS_URL
          value: http://metrics-collector:8000/metrics      
        volumeMounts:
        - name: filestorage-vol 
          mountPath: /data
        - name: modelstorage-vol 
          mountPath: /models  
---    
## diarization service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: diarization
  namespace: aft  
spec:
  replicas: 5
  selector:
    matchLabels:
      app: diarization
  template:
    metadata:
      labels:
        app: diarization
    spec:
      nodeSelector:
        nodetype: transcriber
      volumes:
      - name: filestorage-vol
        persistentVolumeClaim:
          claimName: filestorage
      - name: appstorage-vol
        persistentVolumeClaim:
          claimName: appstorage
      - name: modelstorage-vol
        persistentVolumeClaim:
          claimName: modelstorage-2       
      containers:
      - name: diarization
        image: airenas/list-diarization-service:2.2.633
        env:
        - name: MESSAGESERVER_URL
          value: rabbitmq:5672  
        - name: MESSAGESERVER_USER
          valueFrom:
            secretKeyRef:
              name: rabbit-mq-login
              key: username  
        - name: MESSAGESERVER_PASS
          valueFrom:
            secretKeyRef:
              name: rabbit-mq-login
              key: password
        - name: METRICS_URL
          value: http://metrics-collector:8000/metrics              
        volumeMounts:
        - name: filestorage-vol 
          mountPath: /data
        - name: appstorage-vol 
          mountPath: /apps
        - name: modelstorage-vol 
          mountPath: /models
---  
#transcription dispatcher      
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcription-dispatcher
  namespace: aft  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transcription-dispatcher
  template:
    metadata:
      labels:
        app: transcription-dispatcher
    spec:
      nodeSelector:
        nodetype: transcriber
      volumes:
      - name: filestorage-vol
        persistentVolumeClaim:
          claimName: filestorage
      - name: modelstorage-vol
        persistentVolumeClaim:
          claimName: modelstorage-2        
      containers:
      - name: transcription-dispatcher
        image: airenas/list-dispatcher-service:1.0.701
        env:
        - name: MESSAGESERVER_URL
          value: rabbitmq:5672  
        - name: MESSAGESERVER_USER
          valueFrom:
            secretKeyRef:
              name: rabbit-mq-login
              key: username  
        - name: MESSAGESERVER_PASS
          valueFrom:
            secretKeyRef:
              name: rabbit-mq-login
              key: password
        - name: DISPATCHER_REGISTRATIONQUEUE
          value: TranscriptionWorker_Registry
        - name: DISPATCHER_WORKQUEUE
          value: Transcription
        - name: RECOGNIZERCONFIG_KEY
          value: transcription-preload_key
        - name: STRATEGY_MODELLOADDURATION
          value: 10s
        - name: STRATEGY_REALTIMEFACTOR
          value: "0.4"  
        - name: LOGGER_LEVEL
          value: debug
        volumeMounts:
        - name: filestorage-vol 
          mountPath: /data
        - name: modelstorage-vol 
          mountPath: /models    
---
## transcription service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcription
  namespace: aft  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: transcription
  template:
    metadata:
      labels:
        app: transcription
    spec:
      nodeSelector:
        nodetype: transcriber
      volumes:
      - name: filestorage-vol
        persistentVolumeClaim:
          claimName: filestorage
      - name: appstorage-vol
        persistentVolumeClaim:
          claimName: appstorage
      - name: modelstorage-vol
        persistentVolumeClaim:
          claimName: modelstorage-2        
      containers:
      - name: transcription
        image: airenas/list-transcription-service:3.2.633
        env:
        - name: MESSAGESERVER_URL
          value: rabbitmq:5672  
        - name: MESSAGESERVER_USER
          valueFrom:
            secretKeyRef:
              name: rabbit-mq-login
              key: username  
        - name: MESSAGESERVER_PASS
          valueFrom:
            secretKeyRef:
              name: rabbit-mq-login
              key: password
        - name: METRICS_URL
          value: http://metrics-collector:8000/metrics      
        volumeMounts:
        - name: filestorage-vol 
          mountPath: /data
        - name: appstorage-vol 
          mountPath: /apps
        - name: modelstorage-vol 
          mountPath: /models
---  
#rescore dispatcher      
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rescore-dispatcher
  namespace: aft  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rescore-dispatcher
  template:
    metadata:
      labels:
        app: rescore-dispatcher
    spec:
      nodeSelector:
        nodetype: transcriber
      volumes:
      - name: filestorage-vol
        persistentVolumeClaim:
          claimName: filestorage
      - name: modelstorage-vol
        persistentVolumeClaim:
          claimName: modelstorage-2        
      containers:
      - name: rescore-dispatcher
        image: airenas/list-dispatcher-service:1.0.701
        env:
        - name: MESSAGESERVER_URL
          value: rabbitmq:5672  
        - name: MESSAGESERVER_USER
          valueFrom:
            secretKeyRef:
              name: rabbit-mq-login
              key: username  
        - name: MESSAGESERVER_PASS
          valueFrom:
            secretKeyRef:
              name: rabbit-mq-login
              key: password
        - name: DISPATCHER_REGISTRATIONQUEUE
          value: RescoreWorker_Registry
        - name: DISPATCHER_WORKQUEUE
          value: Rescore
        - name: RECOGNIZERCONFIG_KEY
          value: rescore-preload_key
        - name: STRATEGY_MODELLOADDURATION
          value: 1m
        - name: STRATEGY_REALTIMEFACTOR
          value: "0.5"  
        - name: LOGGER_LEVEL
          value: debug
        volumeMounts:
        - name: filestorage-vol 
          mountPath: /data
        - name: modelstorage-vol 
          mountPath: /models    
---    
## rescore worker
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rescore
  namespace: aft  
spec:
  replicas: 4
  selector:
    matchLabels:
      app: rescore
  template:
    metadata:
      labels:
        app: rescore
    spec:
      nodeSelector:
        nodetype: transcriber
      volumes:
      - name: filestorage-vol
        persistentVolumeClaim:
          claimName: filestorage
      - name: appstorage-vol
        persistentVolumeClaim:
          claimName: appstorage
      - name: modelstorage-vol
        persistentVolumeClaim:
          claimName: modelstorage-2        
      containers:
      - name: rescore
        image: airenas/list-rescore-service:1.1.633
        env:
        - name: MESSAGESERVER_URL
          value: rabbitmq:5672  
        - name: MESSAGESERVER_USER
          valueFrom:
            secretKeyRef:
              name: rabbit-mq-login
              key: username  
        - name: MESSAGESERVER_PASS
          valueFrom:
            secretKeyRef:
              name: rabbit-mq-login
              key: password
        - name: METRICS_URL
          value: http://metrics-collector:8000/metrics
        - name: LOGGER_LEVEL
          value: debug  
        volumeMounts:
        - name: filestorage-vol 
          mountPath: /data
        - name: appstorage-vol 
          mountPath: /apps
        - name: modelstorage-vol 
          mountPath: /models
---    
## resultmake worker
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-make
  namespace: aft  
spec:
  replicas: 4
  selector:
    matchLabels:
      app: result-make
  template:
    metadata:
      labels:
        app: result-make
    spec:
      nodeSelector:
        nodetype: transcriber
      volumes:
      - name: filestorage-vol
        persistentVolumeClaim:
          claimName: filestorage
      - name: appstorage-vol
        persistentVolumeClaim:
          claimName: appstorage
      - name: modelstorage-vol
        persistentVolumeClaim:
          claimName: modelstorage-2        
      containers:
      - name: result-make
        image: airenas/list-result-make-service:3.4.693
        env:
        - name: MESSAGESERVER_URL
          value: rabbitmq:5672  
        - name: MESSAGESERVER_USER
          valueFrom:
            secretKeyRef:
              name: rabbit-mq-login
              key: username  
        - name: MESSAGESERVER_PASS
          valueFrom:
            secretKeyRef:
              name: rabbit-mq-login
              key: password
        - name: PR_URL
          value: http://punctuation:8000/punctuationArray
        - name: METRICS_URL
          value: http://metrics-collector:8000/metrics
        volumeMounts:
        - name: filestorage-vol 
          mountPath: /data
        - name: appstorage-vol 
          mountPath: /apps
        - name: modelstorage-vol 
          mountPath: /models
---    
### tensorflow service
apiVersion: v1
kind: Service
metadata:
  name: tensorflow
  namespace: aft
spec:
  type: ClusterIP
  ports:
  - name: client-in
    port: 8500
    protocol: TCP
    targetPort: 8500 
  selector:
    app: tensorflow
---   
## tensorflow
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tensorflow
  namespace: aft  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tensorflow
  template:
    metadata:
      labels:
        app: tensorflow
    spec:
      nodeSelector:
        nodetype: transcriber
      volumes:
      - name: punctuationstorage-vol
        persistentVolumeClaim:
          claimName: punctuationstorage
      containers:
      - name: tensorflow
        image: tensorflow/serving:1.14.0
        env:
        - name: MODEL_NAME
          value: punctuation  
        - name: MODEL_BASE_PATH
          value: /models/model
        volumeMounts:
        - name: punctuationstorage-vol 
          mountPath: /models
---
### punctuation service
apiVersion: v1
kind: Service
metadata:
  name: punctuation
  namespace: aft
spec:
  type: ClusterIP
  ports:
  - name: client-in
    port: 8000
    protocol: TCP
    targetPort: 8000 
  selector:
    app: punctuation
---    
## punctuation
apiVersion: apps/v1
kind: Deployment
metadata:
  name: punctuation
  namespace: aft  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: punctuation
  template:
    metadata:
      labels:
        app: punctuation
    spec:
      nodeSelector:
        nodetype: transcriber
      volumes:
      - name: punctuationstorage-vol
        persistentVolumeClaim:
          claimName: punctuationstorage
      containers:
      - name: punctuation
        image: airenas/list-punctuation-service:2.1.669
        env:
        - name: TF_URL
          value: tensorflow:8500  
        volumeMounts:
        - name: punctuationstorage-vol 
          mountPath: /model
### clean service
---
apiVersion: v1
kind: Service
metadata:
  name: clean
  namespace: aft
spec:
  type: ClusterIP
  ports:
  - name: client-in
    port: 8000
    protocol: TCP
    targetPort: 8000 
  selector:
    app: clean
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clean
  namespace: aft  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clean
  template:
    metadata:
      labels:
        app: clean
    spec:
      nodeSelector:
        nodetype: transcriber
      volumes:
      - name: filestorage-vol
        persistentVolumeClaim:
          claimName: filestorage
      containers:
      - name: clean
        image: airenas/list-clean-service:1.1.668
        ports:
        - containerPort: 8000
          name: client
        env:
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongo-login
              key: username  
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: mongo-login
              key: password      
        - name: MONGO_URL
          value: mongodb://$(MONGO_USER):$(MONGO_PASS)@mongo:27017
        volumeMounts:
        - name: filestorage-vol 
          mountPath: /data
