### upload service
---
apiVersion: v1
kind: Service
metadata:
  name: upload
  namespace: aft
spec:
  type: ClusterIP
  ports:
  - name: client-in
    port: 8000
    protocol: TCP
    targetPort: 8000 
  selector:
    app: upload
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload
  namespace: aft  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload
  template:
    metadata:
      labels:
        app: upload
    spec:
      nodeSelector:
        nodetype: transcriber
      volumes:
      - name: filestorage-vol
        persistentVolumeClaim:
          claimName: filestorage
      containers:
      - name: upoad
        image: airenas/list-upload-service:v0.5beta
        ports:
        - containerPort: 8000
          name: client
        env:
        - name: MESSAGESERVER_URL
          value: rabbitmq:5672  
        - name: MESSAGESERVER_USER
          valueFrom:
            secretKeyRef:
              name: rabbit-mq-login
              key: username  
        - name: MESSAGESERVER_PASS
          valueFrom:
            secretKeyRef:
              name: rabbit-mq-login
              key: password
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongo-login
              key: username  
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: mongo-login
              key: password      
        - name: MONGO_URL
          value: mongodb://$(MONGO_USER):$(MONGO_PASS)@mongo:27017
        volumeMounts:
        - name: filestorage-vol 
          mountPath: /data
---
### status service
apiVersion: v1
kind: Service
metadata:
  name: status
  namespace: aft
spec:
  type: ClusterIP
  ports:
  - name: client-in
    port: 8000
    protocol: TCP
    targetPort: 8000 
  selector:
    app: status
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: status
  namespace: aft  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: status
  template:
    metadata:
      labels:
        app: status
    spec:
      nodeSelector:
        nodetype: transcriber
      containers:
      - name: status
        image: airenas/list-status-service:v0.5beta
        ports:
        - containerPort: 8000
          name: client
        env:
        - name: MESSAGESERVER_URL
          value: rabbitmq:5672  
        - name: MESSAGESERVER_USER
          valueFrom:
            secretKeyRef:
              name: rabbit-mq-login
              key: username  
        - name: MESSAGESERVER_PASS
          valueFrom:
            secretKeyRef:
              name: rabbit-mq-login
              key: password
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongo-login
              key: username  
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: mongo-login
              key: password      
        - name: MONGO_URL
          value: mongodb://$(MONGO_USER):$(MONGO_PASS)@mongo:27017
---
### result service
apiVersion: v1
kind: Service
metadata:
  name: result
  namespace: aft
spec:
  type: ClusterIP
  ports:
  - name: client-in
    port: 8000
    protocol: TCP
    targetPort: 8000 
  selector:
    app: result
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  namespace: aft  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      nodeSelector:
        nodetype: transcriber
      volumes:
      - name: filestorage-vol
        persistentVolumeClaim:
          claimName: filestorage  
      containers:
      - name: result
        image: airenas/list-result-service:v0.5beta
        ports:
        - containerPort: 8000
          name: client
        env:
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongo-login
              key: username  
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: mongo-login
              key: password      
        - name: MONGO_URL
          value: mongodb://$(MONGO_USER):$(MONGO_PASS)@mongo:27017
        volumeMounts:
        - name: filestorage-vol 
          mountPath: /data  
---
### manager service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: aft  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manager
  template:
    metadata:
      labels:
        app: manager
    spec:
      nodeSelector:
        nodetype: transcriber
      containers:
      - name: manager
        image: airenas/list-manager-service:v0.3beta
        env:
        - name: MESSAGESERVER_URL
          value: rabbitmq:5672  
        - name: MESSAGESERVER_USER
          valueFrom:
            secretKeyRef:
              name: rabbit-mq-login
              key: username  
        - name: MESSAGESERVER_PASS
          valueFrom:
            secretKeyRef:
              name: rabbit-mq-login
              key: password
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongo-login
              key: username  
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: mongo-login
              key: password      
        - name: MONGO_URL
          value: mongodb://$(MONGO_USER):$(MONGO_PASS)@mongo:27017
---    
## audio preparation service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audio-prepare
  namespace: aft  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audio-prepare
  template:
    metadata:
      labels:
        app: audio-prepare
    spec:
      nodeSelector:
        nodetype: transcriber
      volumes:
      - name: filestorage-vol
        persistentVolumeClaim:
          claimName: filestorage
      containers:
      - name: audio-prepare
        image: airenas/list-audio-prepare-service:v0.3beta
        env:
        - name: MESSAGESERVER_URL
          value: rabbitmq:5672  
        - name: MESSAGESERVER_USER
          valueFrom:
            secretKeyRef:
              name: rabbit-mq-login
              key: username  
        - name: MESSAGESERVER_PASS
          valueFrom:
            secretKeyRef:
              name: rabbit-mq-login
              key: password
        volumeMounts:
        - name: filestorage-vol 
          mountPath: /data
---    
## diarization service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: diarization
  namespace: aft  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diarization
  template:
    metadata:
      labels:
        app: diarization
    spec:
      nodeSelector:
        nodetype: transcriber
      volumes:
      - name: filestorage-vol
        persistentVolumeClaim:
          claimName: filestorage
      - name: appstorage-vol
        persistentVolumeClaim:
          claimName: appstorage
      - name: diarizationstorage-vol
        persistentVolumeClaim:
          claimName: diarizationstorage        
      containers:
      - name: diarization
        image: airenas/list-diarization-service:v0.3beta
        env:
        - name: MESSAGESERVER_URL
          value: rabbitmq:5672  
        - name: MESSAGESERVER_USER
          valueFrom:
            secretKeyRef:
              name: rabbit-mq-login
              key: username  
        - name: MESSAGESERVER_PASS
          valueFrom:
            secretKeyRef:
              name: rabbit-mq-login
              key: password
        volumeMounts:
        - name: filestorage-vol 
          mountPath: /data
        - name: appstorage-vol 
          mountPath: /apps
        - name: diarizationstorage-vol 
          mountPath: /models
---    
## transcription service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcription
  namespace: aft  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transcription
  template:
    metadata:
      labels:
        app: transcription
    spec:
      nodeSelector:
        nodetype: transcriber
      volumes:
      - name: filestorage-vol
        persistentVolumeClaim:
          claimName: filestorage
      - name: appstorage-vol
        persistentVolumeClaim:
          claimName: appstorage
      - name: modelstorage-vol
        persistentVolumeClaim:
          claimName: modelstorage        
      containers:
      - name: transcription
        image: airenas/list-transcription-service:v0.4beta
        env:
        - name: MESSAGESERVER_URL
          value: rabbitmq:5672  
        - name: MESSAGESERVER_USER
          valueFrom:
            secretKeyRef:
              name: rabbit-mq-login
              key: username  
        - name: MESSAGESERVER_PASS
          valueFrom:
            secretKeyRef:
              name: rabbit-mq-login
              key: password
        volumeMounts:
        - name: filestorage-vol 
          mountPath: /data
        - name: appstorage-vol 
          mountPath: /apps
        - name: modelstorage-vol 
          mountPath: /models
---    
## resultmake service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-make
  namespace: aft  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-make
  template:
    metadata:
      labels:
        app: result-make
    spec:
      nodeSelector:
        nodetype: transcriber
      volumes:
      - name: filestorage-vol
        persistentVolumeClaim:
          claimName: filestorage
      - name: appstorage-vol
        persistentVolumeClaim:
          claimName: appstorage
      - name: modelstorage-vol
        persistentVolumeClaim:
          claimName: modelstorage        
      containers:
      - name: result-make
        image: airenas/list-result-make-service:v0.4beta
        env:
        - name: MESSAGESERVER_URL
          value: rabbitmq:5672  
        - name: MESSAGESERVER_USER
          valueFrom:
            secretKeyRef:
              name: rabbit-mq-login
              key: username  
        - name: MESSAGESERVER_PASS
          valueFrom:
            secretKeyRef:
              name: rabbit-mq-login
              key: password
        volumeMounts:
        - name: filestorage-vol 
          mountPath: /data
        - name: appstorage-vol 
          mountPath: /apps
        - name: modelstorage-vol 
          mountPath: /models
