## rabbitMQ persistence volumes
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq
  namespace: aft
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/aft/rabbitmq"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq
  namespace: aft
spec:
  accessModes:
  - ReadWriteOnce
  volumeName: rabbitmq
  resources:
     requests:
       storage: 1Gi  
---       
## mongo persistence volumes
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo
  namespace: aft
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/aft/mongo"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo
  namespace: aft
spec:
  accessModes:
  - ReadWriteOnce
  volumeName: mongo
  resources:
     requests:
       storage: 2Gi  
---        
## file storage persistence volumes
apiVersion: v1
kind: PersistentVolume
metadata:
  name: filestorage
  namespace: aft
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/aft/filestorage"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filestorage
  namespace: aft
spec:
  accessModes:
  - ReadWriteOnce
  volumeName: filestorage
  resources:
     requests:
       storage: 5Gi  
---         
## apps storage persistence volumes
apiVersion: v1
kind: PersistentVolume
metadata:
  name: appstorage
  namespace: aft
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/aft/appstorage"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appstorage
  namespace: aft
spec:
  accessModes:
  - ReadWriteOnce
  volumeName: appstorage
  resources:
     requests:
       storage: 1Gi  
---       
## punctuation model persistence volumes
apiVersion: v1
kind: PersistentVolume
metadata:
  name: punctuationstorage
  namespace: aft
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/aft/punctuationstorage"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: punctuationstorage
  namespace: aft
spec:
  accessModes:
  - ReadWriteOnce
  volumeName: punctuationstorage
  resources:
     requests:
       storage: 2Gi   
---       
## models persistence volumes
apiVersion: v1
kind: PersistentVolume
metadata:
  name: modelstorage-2
  namespace: aft
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/aft/modelstorage-2"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: modelstorage-2
  namespace: aft
spec:
  accessModes:
  - ReadWriteOnce
  volumeName: modelstorage-2
  resources:
     requests:
       storage: 200Gi   

---       
## kafka integration persistence storage
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafkaintegrationstorage
  namespace: aft
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/aft/kafkaintegrationstorage"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafkaintegrationstorage
  namespace: aft
spec:
  accessModes:
  - ReadWriteOnce
  volumeName: kafkaintegrationstorage
  resources:
     requests:
       storage: 1Gi                                                     