-include Makefile.options.local

WORK_DIR?=am
INITIAL?=ben-2.0
INITIAL_DIR?=am/$(INITIAL)

INITIAL_FILE?=am-$(INITIAL).tar.gz

INITIAL_CONFIG_FILE?=config-$(INITIAL).tar.gz

NAME?=ben-tel
VERSION?=1.1

dwn_url=https://semantikadocker.vdu.lt/models

