rule_files:
  - prometheus_rules.yml
  
scrape_configs:
- job_name: 'node-exporter'
  scrape_interval: 30s
  static_configs:
  - targets:
    - node-exporter:9100

- job_name: 'rabbitmq-exporter'
  scrape_interval: 30s
  static_configs:
  - targets:
    - rabbitmq-exporter:9419    
