version: '3.1'

services:
  proxy:
    image: traefik:2.3.1 
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./traefik.toml:/traefik.toml:ro
      - ./rules.toml:/rules.toml:ro
    ports:
      - "80:80" 
      - "443:443"
      - "8080:8080"
    restart: unless-stopped

  web:
    image: ${DOCKER_REPO}ear-app:${EAR_APP_VERSION}
    restart: unless-stopped  
    environment:
      BASE_HREF: /${URL}/
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.web.rule=PathPrefix(`/{path:(?i)ausis}/`)"
     - "traefik.http.routers.web.priority=5"
     - "traefik.http.routers.web.middlewares=web"
     - "traefik.http.middlewares.web.stripprefix.prefixes=/ausis"
     - "traefik.http.routers.web.entrypoints=web,websecure"
     - "traefik.http.routers.web.tls=true"
     - "traefik.http.routers.web.service=web"
     - "traefik.http.services.web.loadbalancer.server.port=8000"

  editor:
    image: ${DOCKER_REPO}editor-app:0.1.4
    restart: unless-stopped
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.editor.rule=PathPrefix(`/{path:(?i)ausis/editor}/`)"
     - "traefik.http.routers.editor.middlewares=editor"
     - "traefik.http.middlewares.editor.stripprefix.prefixes=/ausis/editor"
     - "traefik.http.routers.editor.entrypoints=web,websecure"
     - "traefik.http.routers.editor.tls=true"
     - "traefik.http.routers.editor.service=editor"
     - "traefik.http.services.editor.loadbalancer.server.port=80"      
 
  share:
    image: nginx:1.17.9
    restart: unless-stopped
    volumes:
      - ./share-data:/usr/share/nginx/html
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.share.rule=PathPrefix(`/.well-known/`)"
     - "traefik.http.routers.share.priority=5"
     - "traefik.http.routers.share.entrypoints=web,websecure"
     - "traefik.http.routers.share.tls=true"
     - "traefik.http.routers.share.service=share"
     - "traefik.http.services.share.loadbalancer.server.port=80"
