OUTPUT_ROOT=/home/airenas/projects/list/volumes/fileStorage/decoded
RESULTS_ROOT=/home/airenas/projects/list/volumes/fileStorage/decoded/trans
INPUT_ROOT=/home/airenas/projects/list/volumes/fileStorage/decoded
APPS_ROOT=/home/airenas/projects/list/volumes/apps/kaldi
MODELS_ROOT=/home/airenas/hdd/list/graph_w63g

