name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2


    - name: Get dependencies
      working-directory: ./src/tools
      run: |
        go get -a ./...

    - name: Build
      working-directory: ./src/tools
      run: go build -v ./...  

    - name: Test 
      working-directory: ./src/tools
      run: |
        make generate/mocks
        make test/report

    - name: Run vet & lint
      working-directory: ./src/tools
      run: | 
        make generate/mocks
        make test/lint
 
